language: python
matrix:
  include:
    - python: 2.6
      dist: trusty
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7


# command to run tests
script: py.test
